version: '3'

services:
  httpd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - connected-by-ai-node_modules:/workspace/frontend/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: postgres:15.2
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - '5432:5432'
    volumes:
      - connected-by-ai-postgres:/var/lib/postgresql/data

volumes:
  connected-by-ai-node_modules:
  connected-by-ai-postgres: